# This workflow publishes any commits onto master to gh-pages
name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies and build
        run: |
          cd website/
          yarn install
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website/build/bigboizanddiana.com
          PRESERVE: true
